# Generated by Django 3.2.6 on 2021-11-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_car_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='car',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
