# Generated by Django 3.2.6 on 2021-11-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_car_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='model',
            old_name='brand_id',
            new_name='brand',
        ),
    ]
