# Generated by Django 3.2.6 on 2021-11-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_newuser_is_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='phone',
            field=models.CharField(default='', max_length=30),
        ),
    ]
