# Generated by Django 3.2.6 on 2021-11-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_number',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
